-- Script simplificado de instalación
-- Eliminar tabla si existe
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE alumnos_universidad CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- Crear tabla en una sola línea
CREATE TABLE alumnos_universidad (id_alumno NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, matricula VARCHAR2(50) NOT NULL UNIQUE, nombre_completo VARCHAR2(255) NOT NULL, carrera VARCHAR2(100) NOT NULL, semestre NUMBER(2) NOT NULL, status VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL, email_institucional VARCHAR2(255) NOT NULL, fecha_ingreso DATE DEFAULT SYSDATE NOT NULL, fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT ck_alumno_univ_semestre CHECK (semestre BETWEEN 1 AND 12), CONSTRAINT ck_alumno_univ_status CHECK (status IN ('ACTIVO', 'INACTIVO', 'EGRESADO', 'BAJA')));

-- Insertar datos
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A12345678', 'Juan Pérez García', 'Ingeniería en Sistemas', 5, 'ACTIVO', 'juan.perez@universidad.edu.mx', TO_DATE('2023-08-15', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A87654321', 'María López Hernández', 'Mercadotecnia', 3, 'ACTIVO', 'maria.lopez@universidad.edu.mx', TO_DATE('2024-01-20', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A11223344', 'Carlos Ramírez Torres', 'Administración de Empresas', 7, 'ACTIVO', 'carlos.ramirez@universidad.edu.mx', TO_DATE('2022-08-15', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A55667788', 'Ana Martínez Ruiz', 'Diseño Gráfico', 4, 'ACTIVO', 'ana.martinez@universidad.edu.mx', TO_DATE('2023-08-15', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A99887766', 'Luis González Vega', 'Contaduría Pública', 6, 'ACTIVO', 'luis.gonzalez@universidad.edu.mx', TO_DATE('2022-08-15', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A22334455', 'Laura Sánchez Flores', 'Mercadotecnia', 2, 'ACTIVO', 'laura.sanchez@universidad.edu.mx', TO_DATE('2024-08-15', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A66778899', 'Pedro Morales Castro', 'Ingeniería Industrial', 8, 'ACTIVO', 'pedro.morales@universidad.edu.mx', TO_DATE('2021-08-15', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A33445566', 'Sofia Rivera Mendoza', 'Psicología', 3, 'ACTIVO', 'sofia.rivera@universidad.edu.mx', TO_DATE('2024-01-20', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A99998888', 'Roberto Torres Díaz', 'Derecho', 5, 'INACTIVO', 'roberto.torres@universidad.edu.mx', TO_DATE('2023-01-20', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A77776666', 'Diana Ortiz Jiménez', 'Arquitectura', 12, 'EGRESADO', 'diana.ortiz@universidad.edu.mx', TO_DATE('2019-08-15', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A10101010', 'Fernando Castro López', 'Mercadotecnia', 5, 'ACTIVO', 'fernando.castro@universidad.edu.mx', TO_DATE('2023-08-15', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A20202020', 'Gabriela Núñez Silva', 'Comunicación', 4, 'ACTIVO', 'gabriela.nunez@universidad.edu.mx', TO_DATE('2023-08-15', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A30303030', 'Ricardo Herrera Ramos', 'Finanzas', 6, 'ACTIVO', 'ricardo.herrera@universidad.edu.mx', TO_DATE('2022-08-15', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A40404040', 'Valeria Cruz Medina', 'Turismo', 3, 'ACTIVO', 'valeria.cruz@universidad.edu.mx', TO_DATE('2024-01-20', 'YYYY-MM-DD'));
INSERT INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) VALUES ('A50505050', 'Miguel Ángel Vargas Pérez', 'Ingeniería Civil', 7, 'ACTIVO', 'miguel.vargas@universidad.edu.mx', TO_DATE('2022-08-15', 'YYYY-MM-DD'));
COMMIT;

-- Verificar
SELECT COUNT(*) as total FROM alumnos_universidad;
SELECT status, COUNT(*) as cantidad FROM alumnos_universidad GROUP BY status ORDER BY status;

PROMPT Instalacion completada. Total de alumnos insertados.
EXIT;
