-- oracle/init/02_create_schema.sql

-- 1. Asegurar entorno correcto
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = congreso_user;

-- 2. Limpieza previa (por si acaso)
BEGIN
    FOR rec IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || rec.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 3. Crear Tablas (Versión Final con qr_code_data)

CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    matricula VARCHAR2(50),
    semestre NUMBER(2),
    telefono VARCHAR2(20),
    rol VARCHAR2(20) DEFAULT 'alumno',
    qr_code_data VARCHAR2(255), 
    codigo_verificacion VARCHAR2(6),
    fecha_codigo TIMESTAMP,
    verificado NUMBER(1) DEFAULT 0,
    intentos_verificacion NUMBER DEFAULT 0,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_qr UNIQUE (qr_code_data)
);

CREATE TABLE administradores (
    id_admin NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    rol VARCHAR2(20) DEFAULT 'staff',
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE eventos (
    id_evento NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre_evento VARCHAR2(255) NOT NULL,
    descripcion CLOB,
    fecha_inicio DATE NOT NULL,
    hora_inicio TIMESTAMP NOT NULL,
    fecha_fin DATE NOT NULL,
    hora_fin TIMESTAMP NOT NULL,
    lugar VARCHAR2(255),
    ponente VARCHAR2(255),
    cupo_maximo NUMBER,
    cupo_actual NUMBER DEFAULT 0,
    genera_constancia NUMBER(1) DEFAULT 0,
    tipo_evento VARCHAR2(20) DEFAULT 'conferencia',
    horas_para_constancia NUMBER(4,2) DEFAULT 1.00
);

CREATE TABLE inscripciones (
    id_inscripcion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_evento NUMBER NOT NULL,
    fecha_inscripcion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR2(20) DEFAULT 'Inscrito',
    CONSTRAINT fk_insc_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_insc_evento FOREIGN KEY (id_evento) REFERENCES eventos(id_evento) ON DELETE CASCADE
);

CREATE TABLE asistencia (
    id_asistencia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_evento NUMBER NOT NULL,
    fecha DATE NOT NULL,
    hora_entrada TIMESTAMP,
    hora_salida TIMESTAMP,
    duracion VARCHAR2(50), 
    estado_asistencia VARCHAR2(20),
    metodo_registro VARCHAR2(20) DEFAULT 'QR_SCAN',
    CONSTRAINT fk_asist_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_asist_evento FOREIGN KEY (id_evento) REFERENCES eventos(id_evento) ON DELETE CASCADE
);

CREATE TABLE constancias (
    id_constancia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_evento NUMBER NOT NULL,
    numero_serie VARCHAR2(100) NOT NULL UNIQUE,
    fecha_emision TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ruta_archivo_pdf VARCHAR2(512),
    CONSTRAINT fk_const_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_const_evento FOREIGN KEY (id_evento) REFERENCES eventos(id_evento) ON DELETE CASCADE
);

CREATE TABLE justificaciones (
    id_justificacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_evento NUMBER NOT NULL,
    fecha_falta DATE NOT NULL,
    motivo CLOB NOT NULL,
    archivo_adjunto_ruta VARCHAR2(512),
    estado VARCHAR2(20) DEFAULT 'PENDIENTE',
    fecha_solicitud TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_revision TIMESTAMP,
    id_admin_revisor NUMBER,
    CONSTRAINT fk_just_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_just_evento FOREIGN KEY (id_evento) REFERENCES eventos(id_evento) ON DELETE CASCADE
);

CREATE TABLE tokens_reseteo_password (
    id_token NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    selector VARCHAR2(255) NOT NULL,
    token_hash VARCHAR2(255) NOT NULL,
    id_usuario NUMBER,
    id_admin NUMBER,
    email VARCHAR2(255) NOT NULL,
    fecha_expiracion TIMESTAMP NOT NULL,
    CONSTRAINT fk_reset_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_reset_admin FOREIGN KEY (id_admin) REFERENCES administradores(id_admin) ON DELETE CASCADE
);

COMMIT;
EXIT;