-- =====================================================
-- Script: 02_create_schema.sql
-- Descripción: Esquema de base de datos para el Sistema de Gestión del Congreso de Mercadotecnia
-- Base de datos: Oracle Database 23ai Free
-- Migrado desde: MySQL 8.0
-- =====================================================

-- Conectar como congreso_user (este script se ejecuta como SYSTEM, luego cambiamos)
WHENEVER SQLERROR EXIT SQL.SQLCODE

-- =====================================================
-- ELIMINAR TABLAS SI EXISTEN (para desarrollo)
-- =====================================================

DECLARE
    v_count NUMBER;
BEGIN
    FOR rec IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || rec.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- =====================================================
-- CREAR TABLAS
-- =====================================================

-- -----------------------------------------------------
-- Tabla: USUARIOS
-- -----------------------------------------------------
CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    matricula VARCHAR2(50),
    semestre NUMBER(2),
    telefono VARCHAR2(20),
    rol VARCHAR2(20) DEFAULT 'alumno' NOT NULL,
    codigo_qr VARCHAR2(255),
    codigo_verificacion VARCHAR2(6),
    fecha_codigo TIMESTAMP,
    verificado NUMBER(1) DEFAULT 0 NOT NULL,
    intentos_verificacion NUMBER DEFAULT 0 NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_matricula UNIQUE (matricula),
    CONSTRAINT uk_usuarios_qr UNIQUE (codigo_qr),
    CONSTRAINT ck_usuarios_rol CHECK (rol IN ('alumno', 'profesor')),
    CONSTRAINT ck_usuarios_semestre CHECK (semestre BETWEEN 1 AND 12),
    CONSTRAINT ck_usuarios_verificado CHECK (verificado IN (0, 1))
);

COMMENT ON TABLE usuarios IS 'Tabla de usuarios del sistema (alumnos y profesores)';
COMMENT ON COLUMN usuarios.id_usuario IS 'Identificador único del usuario';
COMMENT ON COLUMN usuarios.codigo_qr IS 'Datos únicos para generar código QR del usuario';
COMMENT ON COLUMN usuarios.telefono IS 'Número de teléfono en formato internacional (+52XXXXXXXXXX)';
COMMENT ON COLUMN usuarios.codigo_verificacion IS 'Código de verificación de 6 dígitos';
COMMENT ON COLUMN usuarios.verificado IS '0 = No verificado, 1 = Verificado';
COMMENT ON COLUMN usuarios.intentos_verificacion IS 'Contador de intentos fallidos de verificación';

-- -----------------------------------------------------
-- Tabla: ADMINISTRADORES
-- -----------------------------------------------------
CREATE TABLE administradores (
    id_admin NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    rol VARCHAR2(20) DEFAULT 'staff' NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_admin_email UNIQUE (email),
    CONSTRAINT ck_admin_rol CHECK (rol IN ('superadmin', 'staff'))
);

COMMENT ON TABLE administradores IS 'Tabla de administradores del sistema';
COMMENT ON COLUMN administradores.rol IS 'Rol del administrador: superadmin o staff';

-- -----------------------------------------------------
-- Tabla: EVENTOS
-- -----------------------------------------------------
CREATE TABLE eventos (
    id_evento NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre_evento VARCHAR2(255) NOT NULL,
    descripcion CLOB,
    fecha_inicio DATE NOT NULL,
    hora_inicio TIMESTAMP NOT NULL,
    fecha_fin DATE NOT NULL,
    hora_fin TIMESTAMP NOT NULL,
    lugar VARCHAR2(255),
    ponente VARCHAR2(255),
    cupo_maximo NUMBER(11),
    cupo_actual NUMBER(11) DEFAULT 0 NOT NULL,
    genera_constancia NUMBER(1) DEFAULT 0 NOT NULL,
    tipo_evento VARCHAR2(20) DEFAULT 'conferencia' NOT NULL,
    horas_para_constancia NUMBER(4,2) DEFAULT 1.00 NOT NULL,
    CONSTRAINT ck_eventos_tipo CHECK (tipo_evento IN ('conferencia', 'taller')),
    CONSTRAINT ck_eventos_genera_const CHECK (genera_constancia IN (0, 1)),
    CONSTRAINT ck_eventos_cupo CHECK (cupo_actual <= cupo_maximo OR cupo_maximo IS NULL)
);

COMMENT ON TABLE eventos IS 'Tabla de eventos del congreso';
COMMENT ON COLUMN eventos.genera_constancia IS '0 = No genera, 1 = Genera constancia';
COMMENT ON COLUMN eventos.horas_para_constancia IS 'Horas acreditadas en la constancia';

-- -----------------------------------------------------
-- Tabla: INSCRIPCIONES
-- -----------------------------------------------------
CREATE TABLE inscripciones (
    id_inscripcion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_evento NUMBER NOT NULL,
    fecha_inscripcion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado VARCHAR2(20) DEFAULT 'Inscrito' NOT NULL,
    CONSTRAINT uk_inscripciones_usuario_evento UNIQUE (id_usuario, id_evento),
    CONSTRAINT fk_inscripciones_usuario FOREIGN KEY (id_usuario) 
        REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_inscripciones_evento FOREIGN KEY (id_evento) 
        REFERENCES eventos(id_evento) ON DELETE CASCADE,
    CONSTRAINT ck_inscripciones_estado CHECK (estado IN ('Inscrito', 'Cancelado'))
);

COMMENT ON TABLE inscripciones IS 'Tabla de inscripciones de usuarios a eventos';

-- -----------------------------------------------------
-- Tabla: ASISTENCIA
-- -----------------------------------------------------
CREATE TABLE asistencia (
    id_asistencia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_evento NUMBER NOT NULL,
    fecha DATE NOT NULL,
    hora_entrada TIMESTAMP,
    hora_salida TIMESTAMP,
    duracion INTERVAL DAY TO SECOND,
    estado_asistencia VARCHAR2(20),
    metodo_registro VARCHAR2(20) DEFAULT 'QR_SCAN',
    CONSTRAINT fk_asistencia_usuario FOREIGN KEY (id_usuario) 
        REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_asistencia_evento FOREIGN KEY (id_evento) 
        REFERENCES eventos(id_evento) ON DELETE CASCADE,
    CONSTRAINT ck_asistencia_estado CHECK (estado_asistencia IN ('Completa', 'Incompleta', 'Ausente')),
    CONSTRAINT ck_asistencia_metodo CHECK (metodo_registro IN ('QR_SCAN', 'MANUAL_ADMIN', 'OTRO'))
);

COMMENT ON TABLE asistencia IS 'Tabla de registro de asistencia a eventos';
COMMENT ON COLUMN asistencia.duracion IS 'Duración calculada entre entrada y salida';

-- -----------------------------------------------------
-- Tabla: CONSTANCIAS
-- -----------------------------------------------------
CREATE TABLE constancias (
    id_constancia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_evento NUMBER NOT NULL,
    numero_serie VARCHAR2(100) NOT NULL,
    fecha_emision TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ruta_archivo_pdf VARCHAR2(512),
    CONSTRAINT uk_constancias_serie UNIQUE (numero_serie),
    CONSTRAINT fk_constancias_usuario FOREIGN KEY (id_usuario) 
        REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_constancias_evento FOREIGN KEY (id_evento) 
        REFERENCES eventos(id_evento) ON DELETE CASCADE
);

COMMENT ON TABLE constancias IS 'Tabla de constancias generadas';
COMMENT ON COLUMN constancias.numero_serie IS 'Número de serie único de la constancia';

-- -----------------------------------------------------
-- Tabla: JUSTIFICACIONES
-- -----------------------------------------------------
CREATE TABLE justificaciones (
    id_justificacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_evento NUMBER NOT NULL,
    fecha_falta DATE NOT NULL,
    motivo CLOB NOT NULL,
    archivo_adjunto_ruta VARCHAR2(512),
    estado VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    fecha_solicitud TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_revision TIMESTAMP,
    id_admin_revisor NUMBER,
    CONSTRAINT fk_justif_usuario FOREIGN KEY (id_usuario) 
        REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_justif_evento FOREIGN KEY (id_evento) 
        REFERENCES eventos(id_evento) ON DELETE CASCADE,
    CONSTRAINT fk_justif_admin FOREIGN KEY (id_admin_revisor) 
        REFERENCES administradores(id_admin) ON DELETE SET NULL,
    CONSTRAINT ck_justif_estado CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA'))
);

COMMENT ON TABLE justificaciones IS 'Tabla de justificaciones de inasistencias';

-- -----------------------------------------------------
-- Tabla: TOKENS_RESETEO_PASSWORD
-- -----------------------------------------------------
CREATE TABLE tokens_reseteo_password (
    id_token NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    selector VARCHAR2(255) NOT NULL,
    token_hash VARCHAR2(255) NOT NULL,
    id_usuario NUMBER,
    id_admin NUMBER,
    email VARCHAR2(255) NOT NULL,
    fecha_expiracion TIMESTAMP NOT NULL,
    CONSTRAINT fk_reset_usuario FOREIGN KEY (id_usuario) 
        REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_reset_admin FOREIGN KEY (id_admin) 
        REFERENCES administradores(id_admin) ON DELETE CASCADE
);

COMMENT ON TABLE tokens_reseteo_password IS 'Tabla de tokens para recuperación de contraseña';

-- =====================================================
-- CREAR ÍNDICES PARA OPTIMIZACIÓN
-- =====================================================

-- Índices en tabla asistencia
CREATE INDEX idx_asistencia_usuario ON asistencia(id_usuario);
CREATE INDEX idx_asistencia_evento ON asistencia(id_evento);
CREATE INDEX idx_asistencia_fecha ON asistencia(fecha);

-- Índices en tabla inscripciones
CREATE INDEX idx_inscripciones_usuario ON inscripciones(id_usuario);
CREATE INDEX idx_inscripciones_evento ON inscripciones(id_evento);
CREATE INDEX idx_inscripciones_estado ON inscripciones(estado);

-- Índices en tabla constancias
CREATE INDEX idx_constancias_usuario ON constancias(id_usuario);
CREATE INDEX idx_constancias_evento ON constancias(id_evento);

-- Índices en tabla justificaciones
CREATE INDEX idx_justif_usuario ON justificaciones(id_usuario);
CREATE INDEX idx_justif_evento ON justificaciones(id_evento);
CREATE INDEX idx_justif_estado ON justificaciones(estado);
CREATE INDEX idx_justif_admin ON justificaciones(id_admin_revisor);

-- Índices en tabla tokens_reseteo_password
CREATE INDEX idx_reset_selector ON tokens_reseteo_password(selector);
CREATE INDEX idx_reset_expiracion ON tokens_reseteo_password(fecha_expiracion);

-- =====================================================
-- CREAR TRIGGERS
-- =====================================================

-- Trigger para actualizar cupo_actual cuando se inscribe un usuario
CREATE OR REPLACE TRIGGER trg_inscripcion_incrementar_cupo
AFTER INSERT ON inscripciones
FOR EACH ROW
WHEN (NEW.estado = 'Inscrito')
BEGIN
    UPDATE eventos 
    SET cupo_actual = cupo_actual + 1 
    WHERE id_evento = :NEW.id_evento;
END;
/

-- Trigger para decrementar cupo_actual cuando se cancela una inscripción
CREATE OR REPLACE TRIGGER trg_inscripcion_decrementar_cupo
AFTER UPDATE ON inscripciones
FOR EACH ROW
WHEN (OLD.estado = 'Inscrito' AND NEW.estado = 'Cancelado')
BEGIN
    UPDATE eventos 
    SET cupo_actual = cupo_actual - 1 
    WHERE id_evento = :NEW.id_evento;
END;
/

-- =====================================================
-- INSERTAR DATOS DE PRUEBA (OPCIONAL)
-- =====================================================

-- Insertar un administrador de prueba (contraseña: admin123)
INSERT INTO administradores (nombre_completo, email, password_hash, rol) 
VALUES ('Administrador Principal', 'admin@congreso.com', '$2y$10$YourHashHere', 'superadmin');

-- Confirmar todos los cambios
COMMIT;

-- =====================================================
-- MOSTRAR RESUMEN DE TABLAS CREADAS
-- =====================================================

SELECT 'Tablas creadas exitosamente:' AS mensaje FROM DUAL;

SELECT 
    table_name AS "Tabla",
    num_rows AS "Filas (estimado)"
FROM user_tables
ORDER BY table_name;

SELECT 'Esquema de base de datos creado exitosamente' AS resultado FROM DUAL;

EXIT;
