-- =====================================================
-- Script: 03_create_personalizacion.sql
-- Descripción: Tabla de personalización del sistema
-- Base de datos: Oracle Database 23ai Free
-- =====================================================

-- Conectar a la PDB
ALTER SESSION SET CONTAINER = FREEPDB1;

-- =====================================================
-- Crear tabla de personalización
-- =====================================================

CREATE TABLE personalizacion (
    id_personalizacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    logo_header VARCHAR2(512),
    logo_footer VARCHAR2(512),
    color_primario VARCHAR2(7) DEFAULT '#E4007C' NOT NULL,
    color_secundario VARCHAR2(7) DEFAULT '#FFFFFF' NOT NULL,
    color_texto VARCHAR2(7) DEFAULT '#000000' NOT NULL,
    nombre_institucion VARCHAR2(255) DEFAULT 'UAA' NOT NULL,
    nombre_evento VARCHAR2(255) DEFAULT 'Congreso de Mercadotecnia' NOT NULL,
    pie_constancia VARCHAR2(512),
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_color_primario CHECK (REGEXP_LIKE(color_primario, '^#[0-9A-Fa-f]{6}$')),
    CONSTRAINT ck_color_secundario CHECK (REGEXP_LIKE(color_secundario, '^#[0-9A-Fa-f]{6}$')),
    CONSTRAINT ck_color_texto CHECK (REGEXP_LIKE(color_texto, '^#[0-9A-Fa-f]{6}$'))
);

COMMENT ON TABLE personalizacion IS 'Tabla de personalización visual del sistema';
COMMENT ON COLUMN personalizacion.logo_header IS 'Ruta del logo del encabezado';
COMMENT ON COLUMN personalizacion.logo_footer IS 'Ruta del logo del pie de página';
COMMENT ON COLUMN personalizacion.color_primario IS 'Color primario en formato hexadecimal (#RRGGBB)';
COMMENT ON COLUMN personalizacion.pie_constancia IS 'Texto del pie de página en constancias PDF';

-- Trigger para actualizar fecha_actualizacion automáticamente
CREATE OR REPLACE TRIGGER trg_personalizacion_updated
BEFORE UPDATE ON personalizacion
FOR EACH ROW
BEGIN
    :NEW.fecha_actualizacion := CURRENT_TIMESTAMP;
END;
/

-- =====================================================
-- Insertar valores por defecto
-- =====================================================

INSERT INTO personalizacion (
    nombre_institucion,
    nombre_evento,
    color_primario,
    color_secundario,
    color_texto,
    pie_constancia
) VALUES (
    'Universidad Autónoma de Aguascalientes',
    'Congreso de Mercadotecnia 2025',
    '#E4007C',
    '#FFFFFF',
    '#333333',
    'Universidad Autónoma de Aguascalientes - Congreso de Mercadotecnia'
);

COMMIT;

-- Verificar inserción
SELECT 
    id_personalizacion,
    nombre_institucion,
    nombre_evento,
    color_primario,
    TO_CHAR(fecha_actualizacion, 'YYYY-MM-DD HH24:MI:SS') as fecha_creacion
FROM personalizacion;

SELECT 'Tabla de personalización creada exitosamente' AS resultado FROM DUAL;

EXIT;
