-- =====================================================
-- SCRIPT DE INSTALACIÓN COMPLETO
-- Sistema de Validación de Alumnos Universitarios
-- =====================================================
-- Este script instala todo lo necesario para el sistema
-- de validación de matrículas
-- =====================================================

-- Paso 1: Eliminar tabla si existe (solo para reinstalación)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE alumnos_universidad CASCADE CONSTRAINTS';
   DBMS_OUTPUT.PUT_LINE('✓ Tabla anterior eliminada');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
      DBMS_OUTPUT.PUT_LINE('✓ No existe tabla anterior');
END;
/

-- Paso 2: Crear tabla
CREATE TABLE alumnos_universidad (
    id_alumno NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    matricula VARCHAR2(50) NOT NULL UNIQUE,
    nombre_completo VARCHAR2(255) NOT NULL,
    carrera VARCHAR2(100) NOT NULL,
    semestre NUMBER(2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    email_institucional VARCHAR2(255) NOT NULL,
    fecha_ingreso DATE DEFAULT SYSDATE NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT ck_alumno_univ_semestre CHECK (semestre BETWEEN 1 AND 12),
    CONSTRAINT ck_alumno_univ_status CHECK (status IN ('ACTIVO', 'INACTIVO', 'EGRESADO', 'BAJA'))
);

-- Comentarios
COMMENT ON TABLE alumnos_universidad IS 'Base de datos simulada de alumnos de la universidad';
COMMENT ON COLUMN alumnos_universidad.matricula IS 'Matrícula única del alumno';
COMMENT ON COLUMN alumnos_universidad.status IS 'Estado: ACTIVO, INACTIVO, EGRESADO, BAJA';

-- Paso 3: Insertar datos de prueba
INSERT ALL
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A12345678', 'Juan Pérez García', 'Ingeniería en Sistemas', 5, 'ACTIVO', 'juan.perez@universidad.edu.mx', TO_DATE('2023-08-15', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A87654321', 'María López Hernández', 'Mercadotecnia', 3, 'ACTIVO', 'maria.lopez@universidad.edu.mx', TO_DATE('2024-01-20', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A11223344', 'Carlos Ramírez Torres', 'Administración de Empresas', 7, 'ACTIVO', 'carlos.ramirez@universidad.edu.mx', TO_DATE('2022-08-15', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A55667788', 'Ana Martínez Ruiz', 'Diseño Gráfico', 4, 'ACTIVO', 'ana.martinez@universidad.edu.mx', TO_DATE('2023-08-15', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A99887766', 'Luis González Vega', 'Contaduría Pública', 6, 'ACTIVO', 'luis.gonzalez@universidad.edu.mx', TO_DATE('2022-08-15', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A22334455', 'Laura Sánchez Flores', 'Mercadotecnia', 2, 'ACTIVO', 'laura.sanchez@universidad.edu.mx', TO_DATE('2024-08-15', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A66778899', 'Pedro Morales Castro', 'Ingeniería Industrial', 8, 'ACTIVO', 'pedro.morales@universidad.edu.mx', TO_DATE('2021-08-15', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A33445566', 'Sofia Rivera Mendoza', 'Psicología', 3, 'ACTIVO', 'sofia.rivera@universidad.edu.mx', TO_DATE('2024-01-20', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A99998888', 'Roberto Torres Díaz', 'Derecho', 5, 'INACTIVO', 'roberto.torres@universidad.edu.mx', TO_DATE('2023-01-20', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A77776666', 'Diana Ortiz Jiménez', 'Arquitectura', 12, 'EGRESADO', 'diana.ortiz@universidad.edu.mx', TO_DATE('2019-08-15', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A10101010', 'Fernando Castro López', 'Mercadotecnia', 5, 'ACTIVO', 'fernando.castro@universidad.edu.mx', TO_DATE('2023-08-15', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A20202020', 'Gabriela Núñez Silva', 'Comunicación', 4, 'ACTIVO', 'gabriela.nunez@universidad.edu.mx', TO_DATE('2023-08-15', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A30303030', 'Ricardo Herrera Ramos', 'Finanzas', 6, 'ACTIVO', 'ricardo.herrera@universidad.edu.mx', TO_DATE('2022-08-15', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A40404040', 'Valeria Cruz Medina', 'Turismo', 3, 'ACTIVO', 'valeria.cruz@universidad.edu.mx', TO_DATE('2024-01-20', 'YYYY-MM-DD'))
    
    INTO alumnos_universidad (matricula, nombre_completo, carrera, semestre, status, email_institucional, fecha_ingreso) 
    VALUES ('A50505050', 'Miguel Ángel Vargas Pérez', 'Ingeniería Civil', 7, 'ACTIVO', 'miguel.vargas@universidad.edu.mx', TO_DATE('2022-08-15', 'YYYY-MM-DD'))
SELECT * FROM dual;

COMMIT;

-- Paso 4: Verificación
DECLARE
    v_count NUMBER;
    v_activos NUMBER;
    v_inactivos NUMBER;
    v_egresados NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM alumnos_universidad;
    SELECT COUNT(*) INTO v_activos FROM alumnos_universidad WHERE status = 'ACTIVO';
    SELECT COUNT(*) INTO v_inactivos FROM alumnos_universidad WHERE status = 'INACTIVO';
    SELECT COUNT(*) INTO v_egresados FROM alumnos_universidad WHERE status = 'EGRESADO';
    
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('  INSTALACIÓN COMPLETADA CON ÉXITO');
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('Total de alumnos: ' || v_count);
    DBMS_OUTPUT.PUT_LINE('  - Activos:      ' || v_activos);
    DBMS_OUTPUT.PUT_LINE('  - Inactivos:    ' || v_inactivos);
    DBMS_OUTPUT.PUT_LINE('  - Egresados:    ' || v_egresados);
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('');
    
    IF v_count = 15 THEN
        DBMS_OUTPUT.PUT_LINE('✓ Todos los registros insertados correctamente');
    ELSE
        DBMS_OUTPUT.PUT_LINE('⚠ ADVERTENCIA: Se esperaban 15 registros, se encontraron ' || v_count);
    END IF;
END;
/

-- Mostrar algunos registros de ejemplo
SELECT 
    matricula,
    nombre_completo,
    carrera,
    semestre,
    status
FROM alumnos_universidad
ORDER BY status DESC, matricula
FETCH FIRST 10 ROWS ONLY;

PROMPT 
PROMPT ========================================
PROMPT  Sistema listo para validación
PROMPT ========================================
PROMPT
PROMPT Prueba la validación con:
PROMPT   - Alumno ACTIVO:    A12345678
PROMPT   - Alumno INACTIVO:  A99998888  
PROMPT   - Alumno EGRESADO:  A77776666
PROMPT   - No existe:        A00000000
PROMPT
